ENV_CONFIG:
  jetbot:
    robot_name: 'jetbot-v0'
    wrapped_env: 'learning_racer.agent.teleoperation:TeleoperationEnv'
    parts:
      teleoperator: 'learning_racer.teleoperate:Teleoperator'
  jetbot-auto:
    robot_name: 'jetbot-v0'
    wrapped_env: 'learning_racer.agent.auto_stop:AutoStopEnv'
    parts:
      teleoperator: 'learning_racer.teleoperate:Teleoperator'

SAC_SETTING:
  LOG_INTERVAL: 1
  VERBOSE: 1
  LEARNING_RATE: 3e-4
  ENT_COEF: 'auto_0.1'
  TRAIN_FREQ: 1
  BATCH_SIZE: 64
  GRADIENT_STEPS: 600
  LEARNING_STARTS: 300
  BUFFER_SIZE: 30000
  VARIANTS_SIZE: 32
  IMAGE_CHANNELS: 3
  GAMMA: 0.99
  TAU: 0.02
  USER_SDE_AT_WARMUP: true
  USER_SDE: false
  SDE_SAMPLE_FREQ: 64

REWARD_SETTING:
  REWARD_CRASH: -10
  CRASH_REWARD_WEIGHT: 5
  SPEED_REWARD_WEIGHT: 0.1

AGENT_SETTING:
  # Agent settings
  N_COMMAND_HISTORY: 20
  MIN_SPEED: 0.7 # 0.4
  MAX_SPEED: 0.95 # 0.9